## Welcome to the Numpy Tutorial

In [2]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,46,5],dtype=np.int32)

In [11]:
arr

array([ 1,  2,  3,  4, 46,  5], dtype=int32)

In [12]:
type(arr)

numpy.ndarray

In [17]:
arr.size

6

In [18]:
arr.shape

(6,)

In [19]:
arr.dtype

dtype('int32')

In [21]:
ar=np.array([[2,1,4,2],[4,2,2,6],[8,23,4,53]])

In [22]:
ar

array([[ 2,  1,  4,  2],
       [ 4,  2,  2,  6],
       [ 8, 23,  4, 53]])

In [23]:
type(ar)

numpy.ndarray

In [26]:
range=np.arange(10,20,2)

In [27]:
range

array([10, 12, 14, 16, 18])

In [28]:
range.T

array([10, 12, 14, 16, 18])

In [29]:
ar.T

array([[ 2,  4,  8],
       [ 1,  2, 23],
       [ 4,  2,  4],
       [ 2,  6, 53]])

In [30]:
ar

array([[ 2,  1,  4,  2],
       [ 4,  2,  2,  6],
       [ 8, 23,  4, 53]])

In [31]:
ar.size

12

In [32]:
ar.shape

(3, 4)

In [34]:
ar

array([[ 2,  1,  4,  2],
       [ 4,  2,  2,  6],
       [ 8, 23,  4, 53]])

In [36]:
np.linspace(10,40,8)

array([10.        , 14.28571429, 18.57142857, 22.85714286, 27.14285714,
       31.42857143, 35.71428571, 40.        ])

In [40]:
np.ravel(ar)

array([ 2,  1,  4,  2,  4,  2,  2,  6,  8, 23,  4, 53])

In [44]:
f=ar.flat

In [45]:
for item in f:
    print(item)

2
1
4
2
4
2
2
6
8
23
4
53


In [46]:
np.zeros_like(ar)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
np.count_nonzero(ar)

12

In [52]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
np.random.rand(10)

array([0.95852072, 0.08571106, 0.30237164, 0.56803139, 0.15449893,
       0.0015636 , 0.90498605, 0.71343657, 0.43600695, 0.48627103])

In [64]:
ar

array([[ 2,  1,  4,  2],
       [ 4, 40,  2,  6],
       [ 8, 23,  4, 53]])

In [65]:
ar[1,1]=40

In [66]:
ar

array([[ 2,  1,  4,  2],
       [ 4, 40,  2,  6],
       [ 8, 23,  4, 53]])

In [75]:
ar.argmax(axis=0)

array([2, 1, 0, 2])

In [77]:
ar.argmin(axis=0)

array([0, 0, 1, 0])

In [78]:
ar.argmax()

np.int64(11)

In [82]:
ar[0,1]=41

In [83]:
ar.min()

np.int64(2)

In [84]:
np.ravel(ar)

array([ 2, 41,  4,  2,  4, 40,  2,  6,  8, 23,  4, 53])

In [85]:
ar.argmin(axis=1)

array([0, 2, 2])

In [86]:
ar.argmax(axis=1)

array([1, 1, 3])

In [88]:
ar

array([[ 2, 41,  4,  2],
       [ 4, 40,  2,  6],
       [ 8, 23,  4, 53]])

In [87]:
ar.min(axis=0)

array([ 2, 23,  2,  2])

In [89]:
ar.argmin(axis=0)

array([0, 2, 1, 0])

In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [91]:
a+b
a-b
a*b
a/b


array([0.25, 0.4 , 0.5 ])

In [92]:
a*2

array([2, 4, 6])

In [93]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [94]:
np.sum(a)

np.int64(6)

In [95]:
np.mean(a)

np.float64(2.0)

In [102]:
print(np.min(a))
print(np.max(a))
print(np.average(a))
print(np.sort(a))
print(np.std(a))

1
3
2.0
[1 2 3]
0.816496580927726


In [106]:
print(a[2])

3


In [108]:
ar.argsort(axis=1)

array([[0, 3, 2, 1],
       [2, 0, 3, 1],
       [2, 0, 1, 3]])

In [110]:
print(ar.sort(axis=1))

None


In [111]:
a[a>4]

array([], dtype=int64)

In [112]:
a[a>2]

array([3])

In [115]:
a[a!=2]

array([1, 3])

In [118]:
a[a%2!=0]

array([1, 3])

In [121]:
print(np.dot(a,b))


32


In [129]:
index=[1,2,7]
a=np.array([1,2,3,4,5,6,7,7,8,8])
a
a[index]


array([2, 3, 7])

In [133]:
print(a[a<=7])

[1 2 3 4 5 6 7 7]


In [135]:
print(np.where(a>4))

(array([4, 5, 6, 7, 8, 9]),)


In [143]:
s=np.split(a,5)
s
# a.size

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 7]), array([8, 8])]

In [144]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
b

array([4, 5, 6])

In [150]:
b.size

3

In [161]:
a.itemsize

8

In [164]:
np.save("numpyArr.npy",ar)

In [165]:
load=np.load("numpyArr.npy")

In [166]:
load

array([[ 2,  2,  4, 41],
       [ 2,  4,  6, 40],
       [ 4,  8, 23, 53]])

In [169]:
np.savetxt("demo.txt",a)

In [170]:
ll=np.loadtxt("demo.txt")

In [171]:
ll

array([1., 2., 3., 4., 5., 6., 7., 7., 8., 8.])